config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords" # パスワードリセットのため
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "top#top" # 仮トップページ
  get "top/top"
  resources :events, only: %i[index new create show edit update destroy] do # 掲示板の一覧表示と新規作成画面への設定
    collection do
      get "user_index" # ログインユーザー専用のレース一覧ページ
    end
  end

  get "terms", to: "static_pages#terms", as: :terms
  get "privacy", to: "static_pages#privacy", as: :privacy
  # get "contact", to: "static_pages#contact", as: :contact　独自の回答フォームを作成したくなったらコメントアウト外す
  get "mypage", to: "users#mypage", as: :mypage
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def top; end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/top.html.erb
<div class="hero bg-transparent text-black py-20 border-4 border-gray-400 rounded-lg ">
  <div class="hero-content text-center">
    <div class="max-w-md">
      <h1 class="text-7xl font-bold mb-4">MINI 4 NOTE</h1>
      <p class="text-lg"></p>
    </div>
  </div>
</div>


<div class="py-20 bg-base-200">
  <div class="container mx-auto text-center">
    <h1 class="text-4xl font-bold mb-6"></h1>
    <p class="text-lg mb-4"></p>
    <div class="flex gap-6 justify-center items-center">
      <!-- レース記録を作成するボタン -->
      <%= link_to new_event_path, class: "btn h-40 w-40 text-sm border-4 border-pink-500 bg-transparent text-gray-600 hover:bg-pink-100 flex flex-col items-center justify-center" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-6 w-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
        </svg>
        レース記録
      <% end %>

      <!-- イベント結果一覧ボタン -->
      <%= link_to events_path, class: "btn h-40 w-40 text-sm border-4 border-blue-500 bg-transparent text-gray-600 hover:bg-blue-100 flex flex-col items-center justify-center" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-6 w-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 6.75h12M8.25 12h12m-12 5.25h12M3.75 6.75h.007v.008H3.75V6.75Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0ZM3.75 12h.007v.008H3.75V12Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm-.375 5.25h.007v.008H3.75v-.008Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
        </svg>
        イベント一覧
      <% end %>
    </div>
  </div>
</div>







<!-- フッター追加 -->
<footer class="text-white py-6">
  <div class="container mx-auto text-center">
    <ul class="flex justify-center gap-6">
      <li><%= link_to "利用規約", terms_path, class: "text-gray-600 hover:text-white" %></li>
      <li><%= link_to "プライバシーポリシー", privacy_path, class: "text-gray-600 hover:text-white" %></li>
      <li><%= link_to "お問い合わせ", "https://docs.google.com/forms/d/e/1FAIpQLSdzkx9PdN_mfHkHyve2Fzqa_9fRHw1UXjWeh5yXI8IkiAWN-A/viewform?usp=dialog", class: "text-gray-600 hover:text-white" %></li>
    </ul>
  </div>
</footer>

<div class="flex justify-center items-center my-3">
    <%= link_to "https://github.com/kokichi-cat/Mini-4WD-Race-Management-App", target: "_blank", rel: "noopener noreferrer",class: "mr-3", data: { toggle: "tooltip", placement: "bottom" }, title: "GitHub" do %>
        <%= image_tag 'github-icon.svg', class: "h-6" %>
    <% end %>
    <%= link_to "https://x.com/Mini4Note1238", target: "_blank", rel: "noopener noreferrer",class: "mr-3", data: { toggle: "tooltip", placement: "bottom" }, title: "X" do %>
        <%= image_tag 'x.svg', class: "h-6" %>
    <% end %>
</div>

<div class="text-sm text-center m-3">© <%= Time.current.year %> - MINI4NOTE</div>