config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords" # パスワードリセットのため
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "top#top" # 仮トップページ
  get "top/top"
  resources :events, only: %i[index new create show edit update destroy] do # 掲示板の一覧表示と新規作成画面への設定
    collection do
      get "user_index" # ログインユーザー専用のレース一覧ページ
    end
  end

  get "terms", to: "static_pages#terms", as: :terms
  get "privacy", to: "static_pages#privacy", as: :privacy
  # get "contact", to: "static_pages#contact", as: :contact　独自の回答フォームを作成したくなったらコメントアウト外す
  get "mypage", to: "users#mypage", as: :mypage
end

app/models/event.rb
class Event < ApplicationRecord
  validates :weather, length: { maximum: 255 } # 値が空でない事を確認し、文字数の最大値を制限する　天気
  validates :temperature, length: { maximum: 255 } # 気温
  validates :event_name, presence: true, length: { maximum: 255 } # 大会、イベント名
  validates :venue, presence: true, length: { maximum: 255 } # 店舗
  validates :coment, length: { maximum: 65_535 }
  validates :link, format: { with: URI::DEFAULT_PARSER.make_regexp, allow_blank: true }, if: :link_present?

  belongs_to :user # EventモデルがUserモデルに属している
  validates :user, presence: true # ログイン中のユーザーを自動的に関連付けられるようになる
  has_many :course_photos, dependent: :destroy # コース写真との関連
  has_many :machines, dependent: :destroy # マシーンとの関連
  has_many :race_times, dependent: :destroy # レースタイムとの関連

  accepts_nested_attributes_for :race_times # ネストされたフォームからrace_timeを保存可能にする
  accepts_nested_attributes_for :machines, allow_destroy: true
  accepts_nested_attributes_for :course_photos, allow_destroy: true

  validate :course_photos_count, on: [:create, :update]

  acts_as_taggable_on :tags # :tags はカスタマイズ可能,タグ機能を追加する記述

  # リンクを分割して配列として返すメソッド
  def links
    link.present? ? link.split(",").map(&:strip) : []
  end

  private

  # リンクが存在しているか確認するメソッド
  def link_present?
    link.present?
  end

  def course_photos_count
    # 新しい course_photos の数を確認（削除予定のものを除外）
    current_photos_count = course_photos.reject(&:marked_for_destruction?).size
    if current_photos_count > 3
      errors.add(:course_photos, "は最大3枚までです")
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    # ログインを確認し、未ログインの場合は自動的にログインページへリダイレクトする
    before_action :authenticate_user!, only: %i[new create show edit update destroy]
    before_action :set_event, only: %i[show edit update destroy]
    before_action :authorize_user!, only: %i[edit update destroy]


  # レース記録作成
  def new
    @event = Event.new
    build_associations
  end

  # 全員レース一覧
  def index
    @events = Event.includes(:user, :race_times, :tags)

    if params[:tag].present?
      @events = @events.joins(:tags).where("tags.name LIKE ?", "%#{params[:tag]}%")# .distinct
      # else
      #   @events = Event.all
      #   @events = Event.includes(:user, :race_times)
      #              .order(date: :desc, event_name: :asc, 'race_times.rap_time': :asc)
    end

    if params[:event_name].present?
      @events = @events.where("event_name LIKE ?", "%#{params[:event_name]}%")
    end

    if params[:venue].present?
      @events = @events.where("venue LIKE ?", "%#{params[:venue]}%")
    end

    if params[:user_name].present?
      @events = @events.joins(:user).where("users.name LIKE ?", "%#{params[:user_name]}%")
    end

    # 検索条件が何も指定されていない場合、全てのイベントを取得
    @events = @events.order(date: :desc, event_name: :asc, 'race_times.rap_time': :asc)

    # if params[:tag].blank? && params[:event_name].blank? && params[:venue].blank? && params[:user_name].blank?
    #   @events = Event.includes(:user, :race_times)
    #                  .order(date: :desc, event_name: :asc, 'race_times.rap_time': :asc)
    # else
    #   @events = @events.joins(:race_times, :user, :tags)
    #                    .select("events.*, users.id AS user_id, users.name AS user_name, MIN(race_times.rap_time) AS min_rap_time, tags.id AS tag_id, tags.name AS tag_name")
    #                    .group("events.id, users.id, users.name, race_times.id, tags.id, tags.name")
    #                    .order("min_rap_time ASC")

    # end
  end

  # ログインユーザーだけのレース一覧
  def user_index
    @events = current_user.events.includes(:race_times).order(date: :desc, event_name: :asc, 'race_times.rap_time': :asc) # ログインユーザーのイベントのみ取得
  end



  def show
    if bot_request?
      render layout: "public" # bot用の公開レイアウト（CSS適用可能）
    else
      authenticate_user!
    end
    @event = Event.find(params[:id])
  end


  def create
    @event = current_user.events.build(event_params)
    Rails.logger.debug @event.inspect # デバッグ用にイベントオブジェクトを表示
    if @event.save
      redirect_to @event, notice: "イベントが作成されました！"
    else
      build_associations # 保存に失敗した場合でも関連データが表示されるように再構築
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])

    # 必要に応じて空の関連オブジェクトを追加
    @event.course_photos.build if @event.course_photos.empty?
    @event.machines.each do |machine|
      machine.machine_photos.build if machine.machine_photos.empty?
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: "イベントが更新されました。"
    else
      render :edit
    end
  end

  def destroy
    if @event.destroy
      flash[:notice] = "イベントを削除しました。"
      redirect_to events_path
    else
      flash[:alert] = "削除に失敗しました。"
      redirect_to event_path(@event)
    end
  end

  private

  # 必要な関連データを構築
  def build_associations
    @event.race_times.build if @event.race_times.empty?
    machine = @event.machines.build if @event.machines.empty?
    machine.gimmicks.build if machine.gimmicks.empty?
    machine.breakes.build if machine.breakes.empty?
    machine.mass_dampers.build if machine.mass_dampers.empty?
    machine.machine_photos.build if machine.machine_photos.empty?
    @event.course_photos.build if @event.course_photos.empty?
  end

  # ストロングパラメーター
  def event_params
    params.require(:event).permit(
      :date, :event_name, :venue, :weather, :temperature, :coment, :link, :tag_list,
      course_photos_attributes: [ :id, :image_url, :_destroy ],
      race_times_attributes: [ :id, :rap_time, :course_length, :_destroy ],
      machines_attributes: [
        :id, :machine_name, :frame, :motor, :gear_ratio, :tire_diameter, :tire_type, :voltage, :speed, :other_comments, :body,
        machine_photos_attributes: [ :id, :image_url, :_destroy ],
        gimmicks_attributes: [
          :id, :gimmick_type,
          rollers_attributes: [ :id, :position, :material, :_destroy ]
        ],
        brakes_attributes: [ :id, :name, :color, :_destroy ],
        mass_dampers_attributes: [ :id, :name, :_destroy ]
      ]
    )
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def authorize_user!
    unless @event.user == current_user
      flash[:alert] = "編集権限がありません。"
      redirect_to events_path
    end
  end
end

def bot_request?
  request.user_agent.present? && request.user_agent.include?("Twitterbot")
end

app/views/events/_event_list.html.erb
<!-- イベント結果一覧 -->
<div class="overflow-x-auto">
  <table class="table w-full ">
    <thead class="sticky top-0 ">
      <tr>
      <th class="text-lg font-bold">Date</th>
      <th class="text-lg font-bold">大会名</th>
      <th class="text-lg font-bold">会場名</th>
      <th class="text-lg font-bold">Time[s]</th>
        <% unless local_assigns[:hide_user_name] %> <!-- 条件分岐でユーザー名の列を制御 -->
        <th class="text-lg font-bold">User</th>
        <% end %>
      </tr>
    </thead>
    <tbody class="bg-white">
      <% @events.each do |event| %>
        <tr>
          <!-- 日付 -->
          <td><%= event.date.strftime("%y/%m/%d") %></td>
            
          <!-- 大会名 -->
          <td><%= link_to event.event_name, event_path(event), class: "text-blue-500 underline" %></td>
            
          <!-- 会場名 -->
          <td><%= event.venue %></td>
            
          <!-- タイム -->
          <td>
            <% if event.race_times.present? %>
              <% event.race_times.each do |race_time| %>
                <div><%= number_with_precision(race_time.rap_time, precision: 2) %></div>
              <% end %>
            <% else %>
              <span class="text-gray-500">未登録</span>
            <% end %>
          </td>

          <!-- ユーザー名 -->
          <% unless local_assigns[:hide_user_name] %> <!-- 条件分岐でユーザー名を制御 -->
            <td><%= event.user.name %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/_form.html.erb
<%= form_with(model: @event, local: true) do |f| %>
    <h2 class="text-2xl font-semibold mb-4">イベント情報</h2>
    
    <!-- イベントの日付、名前、会場、天気、気温、コメント -->
    <div class="form-control mb-4">
      <%= f.label :date, "日付", class: "label-text" %>
      <%= f.date_field :date, required: true, class: "input input-bordered" %>
    </div>

    
    <div class="form-control mb-4">
      <%= f.label :event_name, "大会・イベント名", class: "label-text" %>
      <%= f.text_field :event_name, required: true, class: "input input-bordered" %>
    </div>
    
    <div class="form-control mb-4">
      <%= f.label :venue, "会場・店舗名", class: "label-text" %>
      <%= f.text_field :venue, required: true, class: "input input-bordered" %>
    </div>

    <div class="form-control mb-4">
      <%= f.label :link, "会場、イベントリンク (任意,複数のリンクはカンマで区切って入力してください)" %>
      <%= f.text_area :link, class: "textarea textarea-bordered w-full", placeholder: "例: https://example.com, https://another.com" %>
    </div>

    
    <div class="form-control mb-4">
      <%= f.label :weather, "天気", class: "label-text" %>
      <%= f.text_field :weather, class: "input input-bordered" %>
    </div>
    
    <div class="form-control mb-4">
      <%= f.label :temperature, "会場温度", class: "label-text" %>
      <%= f.number_field :temperature, step: 0.1, class: "input input-bordered" %>
    </div>
    
    <div class="form-control mb-4">
      <%= f.label :coment, "コメント", class: "label-text" %>
      <%= f.text_area :coment, class: "textarea textarea-bordered" %>
    </div>
    
    <h3 class="text-xl font-semibold mt-6 mb-4">ラップタイム</h3>
    <%= f.fields_for :race_times do |rt| %>
      <div class="form-control mb-4">
        <%= rt.label :rap_time, "ラップタイム", class: "label-text" %>
        <%= rt.number_field :rap_time, step: 0.001, class: "input input-bordered" %>
      </div>
      <div class="form-control mb-4">
        <%= rt.label :course_length, "コース全長", class: "label-text" %>
        <%= rt.number_field :course_length, step: 0.001, class: "input input-bordered" %>
      </div>
    <% end %>

    <!-- コースフォト複数枚入力フォーム -->
    <h3 class="text-xl font-semibold mt-6 mb-4">コース写真</h3>

    <!-- 画像選択エリア -->
    <div class="form-control mb-4">
      <label class="label-text">画像を3枚まで選択してください</label>
      <!--input type="file" id="image-selector" class="file-input file-input-bordered" multiple accept="image/*" -->
      <%= f.fields_for :course_photos do |photo_form| %>
        <%= photo_form.file_field :image, multiple: true, class: "file-input file-input-bordered", name: "course_photos[]" %>
      <% end %>
      
      <p class="text-sm text-gray-500 mt-2">選択すると下のフォームに自動で反映されます。</p>
    </div>

    <!-- 画像プレビューと登録フォーム -->
    <div id="image-previews" class="flex flex-wrap gap-4">
        <% @event.course_photos.each_with_index do |photo,i| %>
        <div class="image-preview-container" data-index="<%= i %>">
            <!-- プレビュー用 -->
            <div id="preview-<%= i %>" class="image-preview">
            <p class="text-gray-500">画像が未設定です</p>
            </div>
            <!-- 登録用フォーム -->
           <%= photo.image_url.present? ? image_tag(photo.image_url.url, class: "rounded shadow-lg", width: 100) : "" %>
            <%= f.fields_for :course_photo do |photo_form| %>
            <%= photo_form.hidden_field :image_url, id: "image-url-#{i}", class: "hidden-image-url" %>
            <% end %>
            <button
                type="button" onclick="addHiddenFile(<%= i %>)"
            >
                追加
            </button>
            
            <button 
                type="button" onclick="clearHiddenField(<%= i %>)"
            >
                クリア
            </button>
            
        </div>
        <% end %>
    </div>



    
    <h3 class="text-xl font-semibold mt-6 mb-4">マシン情報</h3>
    <%= f.fields_for :machines do |machine| %>
      <div class="form-control mb-4">
        <%= machine.label :machine_name, "マシン名", class: "label-text" %>
        <%= machine.text_field :machine_name, class: "input input-bordered" %>
      </div>

      <h3 class="text-xl font-semibold mt-6 mb-4">マシン写真</h3>
      <%= machine.fields_for :machine_photos do |photo_form| %>
        <div class="form-control mb-4">
          <%= photo_form.label :image_url, "マシン写真", class: "label-text" %>
          <%= photo_form.file_field :image_url, class: "file-input file-input-bordered" %>
    
          <% if photo_form.object.persisted? %>
            <div class="mt-2">
              <%= image_tag photo_form.object.image_url.url, class: "rounded shadow-lg", width: 100 %>
              <label class="label cursor-pointer">
                <%= photo_form.check_box :_destroy %>
                <span class="label-text ml-2">この写真を削除</span>
              </label>
            </div>
          <% end %>
        </div>
      <% end %>

      <!-- 空の関連オブジェクトを追加 -->
      <div class="form-control mb-4">
        <%= machine.fields_for :machine_photos, machine.object.machine_photos.build do |new_photo_form| %>
          <%= new_photo_form.label :image_url, "新しいマシン写真を追加", class: "label-text" %>
          <%= new_photo_form.file_field :image_url, class: "file-input file-input-bordered" %>
        <% end %>
      </div> 


    
      <div class="form-control mb-4">
        <%= machine.label :motor, "モーター", class: "label-text" %>
        <%= machine.select :motor, Machine.motors.keys.map { |key| [I18n.t("activerecord.attributes.machine.motor.#{key}"), key] }, {}, class: "input input-bordered" %>
      </div>
    
      <div class="form-control mb-4">
        <%= machine.label :gear_ratio, "ギア比", class: "label-text" %>
        <%= machine.select :gear_ratio, Machine.gear_ratios.keys.map { |key| [I18n.t("activerecord.attributes.machine.gear_ratio.#{key}"), key] }, {}, class: "input input-bordered" %>
      </div>
    
      <div class="form-control mb-4">
        <%= machine.label :frame, "シャーシ", class: "label-text" %>
        <%= machine.select :frame, Machine.frames.keys.map { |key| [I18n.t("activerecord.attributes.machine.frame.#{key}"), key] }, {}, class: "input input-bordered" %>
      </div>
  
      <div class="form-control mb-4">
        <%= machine.label :tire_diameter, "タイヤ径", class: "label-text" %>
        <%= machine.number_field :tire_diameter, step: 0.001, class: "input input-bordered" %>
      </div>
    
      <div class="form-control mb-4">
        <%= machine.label :tire_type, "タイヤ種", class: "label-text" %>
        <%= machine.text_field :tire_type, class: "input input-bordered" %>
      </div>

      <div class="form-control mb-4">
        <%= machine.label :voltage, "電圧 (V)", class: "label-text" %>
        <%= machine.number_field :voltage, step: 0.001, class: "input input-bordered" %>
      </div>

      <div class="form-control mb-4">
        <%= machine.label :speed, "時速 (km/s)", class: "label-text" %>
        <%= machine.number_field :speed, step: 0.001, class: "input input-bordered" %>
      </div>

      <div class="form-control mb-4">
        <%= machine.label :other_comments, "メモ", class: "label-text" %>
        <%= machine.text_area :other_comments, rows: 3, class: "textarea textarea-bordered" %>
      </div>

    <div class="form-control mb-4">
      <%= machine.label :body, "ボディ", class: "label-text" %>
      <%= machine.text_area :body, class: "input input-bordered" %>
    </div>

    <div class="form-control mb-4">
      <%= f.label :tag_list, "タグ（カンマ区切りで入力）" , class: "label-text"%>
      <%= f.text_field :tag_list, class: "input input-bordered" %>
    </div>
        
    <% end %>
    
    
    
    <%= f.submit "保存する", class: "btn bg-orange-500 text-white hover:bg-orange-300" %>
  <% end %>
  

app/views/events/_search_form.html.erb
<div class="mb-6">
  <%= form_with url: search_path, method: :get, local: true, class: "form-control mx-auto" do |f| %>
    <div class="mb-6 flex">
      <%= f.text_field :tag, placeholder: "タグを入力", class: "input input-bordered w-1/6 flex-1" %>
      <%= f.text_field :event_name, placeholder: "大会名を入力", class: "input input-bordered w-1/6 flex-1" %>
      <%= f.text_field :venue, placeholder: "会場名を入力", class: "input input-bordered w-1/6 flex-1" %>
      <% if show_user_name %>
        <%= f.text_field :user_name, placeholder: "ユーザー名を入力", class: "input input-bordered w-1/6 flex-1" %>
      <% end %>
      <%= f.submit "検索", class: "btn bg-orange-500 text-white hover:bg-orange-300" %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<div class="container mx-auto py-4">
  <h1 class="text-2xl font-bold mb-4">イベントを編集</h1>

  <%= render 'form', event: @event %>
</div>

app/views/events/index.html.erb
<div class="container mx-auto py-4">
  <h1 class="text-2xl font-bold text-center mb-6">みんなのイベント結果一覧</h1>

    <!-- 共通検索フォーム呼び出し -->
    <%= render 'search_form', search_path: events_path, show_user_name: true %>
    <!--
    <div class="mb-6">
    <%= form_with url: events_path, method: :get, local: true, class: "form-control mx-auto" do |f| %>
        <div class="mb-6 flex">
        <%= f.text_field :tag, placeholder: "タグを入力", class: "input input-bordered w-1/6 flex-1" %>
        <%= f.text_field :event_name, placeholder: "大会名を入力", class: "input input-bordered w-1/6 flex-1" %>
        <%= f.text_field :venue, placeholder: "会場名を入力", class: "input input-bordered w-1/6 flex-1" %>
        <%= f.text_field :user_name, placeholder: "ユーザー名を入力", class: "input input-bordered w-1/6 flex-1" %>
        <%= f.submit "検索", class: "btn btn-primary" %>
        </div>
    <% end %>
    -->

    </div>

    

    <!-- 共通テンプレートの呼び出し -->
    <%= render 'event_list', events: @events %>
</div>

app/views/events/new.html.erb
<!-- app/views/events/new.html.erb -->
<div class="container mx-auto py-4">
  <h1 class="text-2xl font-bold mb-4">新しいイベントを作成</h1>

  <%= render 'form', event: @event %>
</div>

app/views/events/show.html.erb
<!-- app/views/events/show.html.erb -->
<h1 class="text-3xl font-bold mb-4 text-gray-700"><%= @event.event_name %></h1>

<div class="text-2xl mb-6 text-gray-600 text-center">
  <% image_url = @event.course_photos.first&.image_url %>
  <% cache_buster = @event.updated_at.to_i if @event.updated_at.present? %>

  <% if image_url.present? %>
    <% assign_meta_tags title: @event.event_name, image: "#{image_url}?v=#{cache_buster}" %>
  <% end %>
  
  <% twitter_text = "#{@event.event_name} 結果\n#ミニ四駆 #mini4wd #MINI4NOTE" %>
  <% twitter_share_url = "https://twitter.com/share?url=#{CGI.escape(event_url(@event))}&text=#{CGI.escape(twitter_text)}" %>

  <%= link_to twitter_share_url, target: '_blank', data: { toggle: "tooltip", placement: "bottom" }, title: "Xでシェア" do %>
    <%= image_tag 'x.svg', alt: 'Xシェアボタン', class: 'h-5 w-5' %>
  <% end %>
</div>



<div class="mb-6">
  <p>Date: <%= @event.date %></p>
  <p>天気: <%= @event.weather %></p>
  <p>会場温度: <%= @event.temperature %>℃</p>
  <p>会場: <%= @event.venue %></p>
  <p>コメント: <%= @event.coment %></p>
</div>

<h2 class="text-2xl font-semibold mb-4">ラップタイム</h2>
<ul>
  <% @event.race_times.each do |time| %>
    <% if time.rap_time.present? %>
      <li>ラップタイム: <%= time.rap_time.round(2) %> s</li>
    <% end %>
    <% if time.course_length.present? %>
      <li>コース全長: <%= time.course_length.round(2) %> m</li>
    <% end %>
  <% end%>
</ul>

<h3 class="text-xl font-semibold mt-6 mb-4">コース写真</h3>
<div class="grid grid-cols-3 gap-4">
  <% @event.course_photos.each do |photo| %>
    <div class="w-full">
      <%= image_tag photo.image_url.url, class: "photo-img" if photo.image_url.present? %>
    </div>
  <% end %>
</div>


<h2 class="text-2xl font-semibold mt-6 mb-4">マシン情報</h2>
<% @event.machines.each do |machine| %>
  <div class="mb-6 rounded-lg">
    <h3 class="text-xl font-semibold">マシン名: <%= machine.machine_name %></h3>
    <p>モーター: <%= I18n.t("activerecord.attributes.machine.motor.#{machine.motor}") %></p>
    <p>ギア比: <%= I18n.t("activerecord.attributes.machine.gear_ratio.#{machine.gear_ratio}") %></p>
    <p>ボディ: <%= machine.body %></p>
    <p>シャーシ: <%= I18n.t("activerecord.attributes.machine.frame.#{machine.frame}") %></p>
    <p>タイヤ径: <%= machine.tire_diameter %> mm</p>
    <p>タイヤ種: <%= machine.tire_type %></p>
    
    <% if @event.user == current_user %>
      <p>電圧: <%= machine.voltage.present? ? format('%.2f', machine.voltage) : '未登録' %> V</p>
      <p>時速: <%= machine.speed %> km/h</p>
      <p>メモ: <%= machine.other_comments %></p>

      <h4 class="text-lg font-semibold mt-4">マシン写真</h4>
      <div class="grid grid-cols-3 gap-4">
        <% machine.machine_photos.each do |photo| %>
          <div class="w-full">
            <%= image_tag photo.image_url.url, class: "rounded shadow-lg" if photo.image_url.present? %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

<div class="flex flex-wrap gap-2 mt-4">
  <% @event.tags.each do |tag| %>
    <%= link_to "# #{tag.name}", events_path(tag: tag.name), class: "px-3 py-1 bg-orange-500 hover:bg-orange-300 text-white rounded-full text-sm shadow" %>
  <% end %>
</div>

<% if @event.link.present? %>
  <p>リンク:</p>
    <ul class="list-disc pl-5">
      <% if @event.links.any? %>
        <% @event.links.each do |url| %>
          <li>
            <%= link_to url, url, target: "_blank", rel: "noopener noreferrer", class: "text-blue-500 hover:underline" %>
          </li>
        <% end %>
      <% else %>
        <li></li>
      <% end %>
    </ul>
<% end %>



<% if @event.user == current_user %>
  <%= link_to '編集', edit_event_path(@event), class: 'btn bg-blue-500 text-white hover:bg-blue-400 ' %>
  <%= link_to '削除', event_path(@event), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn bg-pink-500 text-white hover:bg-pink-400' %>
<% end %>
<%= link_to "戻る", events_path, class: "btn btn-outline mt-6" %>

app/views/events/user_index.html.erb
<div class="container mx-auto py-4">
  <h1 class="text-2xl font-bold text-center mb-6">あなたのイベント結果一覧</h1>

  <!-- 共通検索フォーム呼び出し -->
    <%= render 'search_form', search_path: user_index_events_path, show_user_name: false %>

  <!-- 共通テンプレートの呼び出し -->
  <%= render 'event_list', events: @events, hide_user_name: true %>
</div>